pipelines:
  snitch:
    group: snitch
    label_template: "${snitch[:8]}"
    materials:
      snitch:
        git: https://clearly:d56d91b33e65b7aca2a1a05afd714980fc6b567d@github.com/candidpartners/snitch
        branch: master
        destination: snitch
        whitelist:
        - pipelines.gocd.yaml
        - src/**/*
    stages: &uiStages
      - unit-test:
          clean_workspace: true
          jobs:
            Unit-Test:
              resources:
                - terraform
              tasks:
              - script: |
                  cd snitch/src
                  npm i
                  npm run coverage
      - e2e-test:
          clean_workspace: true
          jobs:
            Unit-Test:
              resources:
                - terraform
              tasks:
              - script: |
                  cd snitch/src
                  npm i
                  npm run test:e2e
      - deploy-to-npm:
          approval:
            type: manual # Require someone in the UI to manually approve the execution of this stage
          clean_workspace: true
          jobs:
            publish-to-npm:
              resources:
                - terraform
              tasks:
              - script: |
                  cd snitch/src
                  npm i --production
                  cd ../
                  ./pipeline/publish-to-npm.sh
      - deploy-website:
          approval:
            type: manual # Require someone in the UI to manually approve the execution of this stage
          clean_workspace: true
          jobs:
            deploy-website:
              resources:
                - terraform
              tasks:
              - script: |
                  cd snitch/ui
                  ./deploy.sh
