provider :
  region : us-west-2
rules :

#CloudTrail
- aws-cloudtrail-ensure-log-file-validation : {}
- aws-cloudtrail-is-enabled-in-all-regions : {}
- aws-cloudtrail-logs-are-encrypted : {}
- aws-cloudtrail-trails-are-integrated-with-cloudwatch-logs : {}

#CloudWatch
- aws-cloudwatch-metric-alarms :
    UnauthorizedAPICalls : true
    ManagementConsoleSignInWithoutMFA : true
    UsageOfRootAccount : true
    IAMPolicyChanges : true
    IAMAccessKeyCreation : true
    IAMUserCreation : true
    CloudTrailConfigurationChanges : true
    AWSManagementConsoleAuthenticationFailures : true
    DisablingOrScheduledDeletionOfCustomerCreatedCMKs : true
    S3BucketPolicyChanges : true
    AWSConfigConfigurationChanges : true
    SecurityGroupChanges : true
    ChangesToNetworkAccessControlLists : true
    ChangesToNetworkGateways : true
    RouteTableChanges : true
    VPCChanges : true

#Config Service
- aws-config-service-is-enabled-in-current-region : {}

#DynamoDB
- aws-dynamodb-encryption :
    exclude :
      - volker-dev-accounts
- aws-dynamodb-point-in-time-recovery-status: {}

#EBS
- aws-ebs-volume-encryption : {}

#EC2
- aws-ec2-ensure-instance-profile : {}
- aws-ec2-ami-includes-sql-server : {}
- aws-ec2-instance-tag-exists :
    names:
      - Name
- aws-ec2-instance-tag-format :
    tags :
      - name : ApplicationCode
      - format : '^[A-Z]{3}$'
      - name : Environment
      - format : ^(DEV|QA|TEST|STAGING|PROD)$
- aws-ec2-key-pair-exists : {}
- aws-ec2-uses-security-group :
    security_groups :
      - "Hello"
      - "World"

#IAM
- aws-iam-account-password-policy :
    MinimumPasswordLength : 14
    MaxPasswordAge: 90
    PasswordReusePrevention: 10
    RequireSymbols : true
    RequireNumbers : true
    RequireUppercaseCharacters : true
    RequireLowercaseCharacters : true
    AllowUsersToChangePassword : true
    ExpirePasswords : true
- aws-iam-avoid-use-of-root-account :
    days : 90
- aws-iam-ensure-a-support-role-is-attached : {}
- aws-iam-ensure-access-keys-are-rotated :
    days : 90
- aws-iam-ensure-master-and-manager-roles-are-active : {}
- aws-iam-ensure-specified-groups-and-roles-exist :
    groups :
      - "Administrators"
      - "Volker.UI"
      - "TEST-GROUP"
    roles :
      - "Admin-Role"
      - "Admin_Role"
      - "TEST-ROLE"
- aws-iam-ensure-unused-credentials-are-disabled :
    days : 90
- aws-iam-hardware-mfa-is-enabled-for-root-account : {}
- aws-iam-mfa-is-enabled-for-iam-users-with-console-password : {}
- aws-iam-mfa-is-enabled-for-root-account : {}
- aws-iam-no-initial-access-keys : {}
- aws-iam-no-policies-use-default-kms-keys: {}
- aws-iam-no-root-account-access-key-exists : {}
- aws-iam-policies-are-attached-only-to-groups-or-roles : {}
- aws-iam-policies-are-least-privileged : {}
- aws-iam-policies-have-requested-region : {}

#KMS
- aws-kms-ensure-key-rotation :
    exclude :
      - cms

#RDS
- aws-rds-encryption-key-exists :
    exclude :
      - vra

#Route53
- aws-route53-no-cloudjack-vulnerabilities :
    route53GoodReferences : true
    route53GoodCnames : true

#S3
- aws-s3-cloudtrail-bucket-access-logging-enabled : {}
- aws-s3-cloudtrail-bucket-is-not-publicly-accessible : {}
- aws-s3-encryption :
    exclude:
      - volker-dev-accounts
- aws-s3-ensure-versioning : {}
- aws-s3-only-allow-encrypted-objects:
    AllowAES256: true

#Security Group
- aws-security-group-allows-inbound :
    cidr : '127.0.0.1/32'
    ports :
     -  '80'
- aws-security-group-allows-outbound :
    cidr : '127.0.0.2/32'
    ports :
      - '22'
- aws-security-group-does-not-allow-inbound :
    cidr : '0.0.0.0/0'
    ports :
      - '22'
      - '3389'
- aws-security-group-does-not-allow-outbound :
    cidr : '204.4.6.2/32'
    ports :
      - '9032-9034'
- aws-security-group-exists : {}

#SNS
- aws-sns-ensure-appropriate-subscribers :
    global_whitelist :
      - arn:aws:lambda:us-west-2:421471939647:function:xray-demo-handler
    topics :
      - topic_arn : arn:aws:sns:us-west-2:421471939647:CIS-NotificationTopic
        topic_whitelist :
          - ethan.bower@candidpartners.com
      - topic_arn : arn:aws:sns:us-west-2:421471939647:CodeBuildPipelineStack-MySNSTopic-11OZQI23UU45L

#VPC
- aws-vpc-default-security-group-restricts-all-traffic :
    enabled : true
- aws-vpc-flow-logs-are-enabled :
    enabled : true
- aws-vpc-no-default-vpc :
    enabled : true
- aws-vpc-routing-tables-for-vpc-peering-are-least-access :
    enabled : true