provider :
  region : us-west-2
rules :
- aws-iam-policies-are-attached-only-to-groups-or-roles : true
- aws-iam-ensure-master-and-manager-roles-are-active : true
- aws-iam-ensure-a-support-role-is-attached : true
- aws-cloudtrail-is-enabled-in-all-regions : true
- aws-cloudtrail-ensure-log-file-validation : true
- aws-s3-cloudtrail-bucket-is-not-publicly-accessible : true
- aws-cloudtrail-trails-are-integrated-with-cloudwatch-logs : true
- aws-kms-ensure-key-rotation: true
- aws-cloudtrail-logs-are-encrypted: true
- aws-cloudtrail-ensure-log-file-validation: true
- aws-iam-does-not-allow-full-access-policies: true
#- aws-iam-account-password-policy : true
- aws-iam-user-policy-does-not-exist : true
- aws-ebs-volume-encryption : true
- aws-vpc-no-default-vpc : true
- aws-s3-encryption:
    exclude:
      - volker-dev-accounts
- aws-rds-encryption-key-exists :
    exclude:
    - none
- aws-dynamodb-encryption :
    exclude:
      - volker-dev-accounts
- aws-ec2-instance-tag-exists :
  - Name
- aws-ec2-instance-tag-format :
  - name : ApplicationCode
    format : '^[A-Z]{3}$'
  - name : Environment
    format : ^(DEV|QA|TEST|STAGING|PROD)$
- aws-ec2-key-pair-exists : true
- aws-ec2-ami-includes-sql-server : false
- aws-security-group-exists : true
- aws-ec2-uses-security-group :
  - sg-24b9b85d
- aws-security-group-does-not-allow-inbound :
    cidr : '204.4.6.2/32'
    port : '9032-9034'
- aws-security-group-does-not-allow-outbound :
    cidr : '204.4.6.2/32'
    port : '9032-9034'
- aws-security-group-allows-inbound :
    cidr : '127.0.0.1/32'
    port : '80'
- aws-security-group-allows-outbound :
    cidr : '127.0.0.2/32'
    port : '22'